### ISSUE TITLE
Video is too short error and Model loading error

### ISSUE THREAD

**Issue by Sidd1609** [yaorong0921/Driver-Intention-Prediction#5]
Hi, I am trying to evaluate using trained 3DResnet models would it be possible to have your version of the trained model as the link provided for the 3DResnet model and the optical flow model is not available. 

Please also provide a more detailed explanation of how to train our own network for both inside and outside.

**Comment by yaorong0921** [comment]
Hi there,
please try the link again.

For training with the videos inside and outside: To reduce computational overhead, I presaved the features from two video streams and utilized multiple layers to process them for obtaining the ultimate outcomes. However, I'm currently searching for the script as it was stored on a server that I may lose access to. I'll share it once I found it.

Best wishes,

**Comment by Sidd1609** [comment]
Thanks, that would be really helpful.

**Comment by Sidd1609** [comment]
Yes, the link is working now. I will test the inference using the trained weights and get back to you. Please could you also provide scripts to manually train for our own version of the dataset.

**Comment by Sidd1609** [comment]
Hi, the zip folder of the optical flow images seems corrupted, I have tried to open it on mac and Linux but keep getting errors. PLease could you check the link.
<img width="288" alt="image" src="https://user-images.githubusercontent.com/48639959/228923455-148428ac-b9f0-4011-ad69-96c9d947b2ce.png">

**Comment by Sidd1609** [comment]
Please also provide information on how to get sample inference results using any data.

**Comment by Sidd1609** [comment]
Do you have any inference scripts, where I could upload an inside and corresponding outside video to the model for predicting output and saving the results?

**Comment by ae208gpu** [comment]
@yaorong0921 Just following up on the inference script, is it possible to run the inference for getting results like the gif file in ReadMe?

**Comment by ae208gpu** [comment]
@yaorong0921 Getting the same issue for flownet images 

Video is too short: ModelData/flownet2_road_camera/lturn/20141019_091623_289_439/
Video is too short:

**Comment by yaorong0921** [comment]
Hi @ae208gpu ,

1. For the gif file, I run the inference to get the prediction and then establish the gif.
2.  Could you please check whether the dataloader works? You get this error maybe because there is no files found in the folder? Did you also get similar error here?: https://github.com/yaorong0921/Driver-Intention-Prediction/issues/2

**Comment by ae208gpu** [comment]
@yaorong0921 

1. Please would you share the inference code for getting the prediction like the gif file?
2. There are image files in the folder for both inside and I use outside images from the link that was provided for optical flow images.
3. Please would you consider also stating how to benchmark your model to evaluate on i) only inside, ii) only outside, and iii) both on inside and outside images. 

Your reply at the earliest would be really helpful.

**Comment by ae208gpu** [comment]
@yaorong0921 I checked the data loader it works fine, but the size of the images in the folder is the issue
please could provide some information on how to fix the issue ?

**Comment by yaorong0921** [comment]
Hi @ae208gpu,
what error did you receive regarding the image size? I have not encountered such an error.

**Comment by ae208gpu** [comment]
Error:
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/anaconda3/envs/DIP/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/anaconda3/envs/DIP/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/anaconda3/envs/DIP/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "Driver-Intention-Prediction/datasets/Brain4cars.py", line 274, in __getitem__
    clip = torch.stack(clip, 0)
RuntimeError: stack expects a non-empty TensorList


Video is too short: flownet2_road_camera/rturn/20141220_161745_1_41/
Video is too short: flownet2_road_camera/end_action/20141019_141117_911_1061/
Video is too short: flownet2_road_camera/end_action/20141019_171211_1042_1192/
Video is too short: flownet2_road_camera/end_action/20141019_165104_768_918/

File does not exists: flownet2_road_camera/end_action/20141019_161013_1127_1277/

-> Please would you share the inference code for getting the prediction like the gif file?
-> There are image files in the folder for both inside and I use outside images from the link that was provided for optical flow images.
-> Please would you consider also stating how to benchmark your model to evaluate on i) only inside, ii) only outside, and iii) both on inside and outside images.

@yaorong0921

**Comment by ae208gpu** [comment]
What is the total size of flownet image folder (the unzipped version)?
@yaorong0921

**Comment by ae208gpu** [comment]
@yaorong0921 how to resolve this issue with flownet images, is it necessary for the flownet images to be inside the road_camera folder of brain4cars.

**Comment by ae208gpu** [comment]
@yaorong0921 getting this error when running bash-Conv.sh

RuntimeError: stack expects a non-empty TensorList
/ssd_scratch/cvit/srisiddarth16541/flownet2_road_camera/lturn/20141115_103835_933_1083/image-0298.png
